#!/usr/bin/env python
import sys

from rdflib import Graph

from knom.stratified import stratified
from knom.util import split_rules_and_facts

g = Graph().parse(sys.argv[1])
rules, facts = split_rules_and_facts(g)
inferred = stratified(facts, rules)

print(inferred.serialize(format="n3"))
