#!/usr/bin/env python
import sys

from rdflib import Graph

from knom import single_pass
from knom.util import split_rules_and_facts

g = Graph().parse(sys.argv[1])
rules, facts = split_rules_and_facts(g)
inferred = Graph(namespace_manager=g.namespace_manager)
for triple in single_pass(facts, rules):
    inferred.add(triple)

print(inferred.serialize(format="n3"))
